server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: https://dev-16235276.okta.com/oauth2/default
    client:
      registration:
        internal-client:
          provider: okta
          authorization-grant-type: client_credentials
          scope: internal
          client-id: 0oagrqgdbquAezS8o5d7
          client-secret: hKE2x31ubI3bzAfDmTfzlI1lNtVsMgCOkQccqbJZzSIM1xjcBe9eDeJ_OXMXB4DN

management:
  tracing:
    sampling:
      probability: 1.0
